### PR TITLE
Fix: Change Electron integration functionality 

### PR DESCRIPTION
**Pull request by timfish**
- Moves event normalisation out from the Electron integration
- Moves instrumented electron breadcrumbs into the Electron integration

This way, if a user sets `defaultIntegrations: false`, path normalisation will still work but the Electron breadcrumbs will no longer be written.

### CODE REVIEW

**Comment by timfish** [comment]
The tests pass but I'm not 100% sure I've moved `normalizeEvent` to the right place

**Comment by jan-auer** [comment]
@timfish could you please rebase?

**Comment by timfish** [comment]
The AppVeyor tests have become rather flaky.

**Comment by jan-auer** [comment]
Not sure what's going on with AppVeyor. Tests have succeeded but the build seems to get stuck repeatedly. Merging this now.

**Pull request merged**
