### PR TITLE
feat: Update Sentry dependencies to 6.17

### PR DESCRIPTION
**Pull request by timfish**

### CODE REVIEW

**Review by AbhiPrasad — APPROVED** [review]
Wonder how much this cuts the electron sdk bundle size.

**Comment by timfish** [comment]
I noticed these changes knock about 8KB from the browser SDK so I'd guess something similar!

Ah, I'm actually going to wait for a stable release before merging this. Just wanted to keep on top of the changes!

**Comment by AbhiPrasad** [comment]
`6.17.2` now out of beta!

**Comment by timfish** [comment]
Thanks for the heads up!

**Review by AbhiPrasad — APPROVED** [review]

**Pull request merged**
